### ISSUE TITLE
[Feature] Compatibility with Jade

### ISSUE THREAD

**Issue by TalEdd** [Aton-Kish/your-reputation#13]
Is it possible for this mod to be compatible with [Jade](https://www.curseforge.com/minecraft/mc-mods/jade). It is also a fork of HWYLA, if I am not wrong.

**Comment by Aton-Kish** [comment]
I never know till I try. But I don't have enough time.

**Comment by TalEdd** [comment]
No rush, maybe a future consideration for this amazing mod project!😊

**Comment by Aton-Kish** [comment]
I uploaded the Jade compatible version.
[Your Reputation v0.2.0+jade.1.19](https://www.curseforge.com/minecraft/mc-mods/your-reputation/files/4275998)
