### ISSUE TITLE
[Request] upload to modrinth

### ISSUE THREAD

**Issue by yesn0t** [Aton-Kish/your-reputation#2]
some key advantages :
* Proper filtering
* Fast searches
* Easier API integration
* In-game discoverability and updates via [ModManager](https://github.com/DeathsGun/ModManager)
* WTHIT is already on modrinth :)
  https://modrinth.com/mod/wthit

btw this mod looks amazing, thanks for making it !

**Comment by Aton-Kish** [comment]
I think Modrinth is certainly useful, but let me think for a moment.
It doesn't offer a rewards program to developers like CurseForge at this time.
I'm developing my mods for me, but It's better to get a reward than not.

**Comment by sternschnaube** [comment]
Hello @Aton-Kish, some time has passed and I think Modrinth offers now a reward program.
Could you please look into that again? Thanks 😊

**Comment by Aton-Kish** [comment]
Thanks for reminding me. I'll look it up.

**Comment by Aton-Kish** [comment]
I have created the Modrinth project!
<https://modrinth.com/mod/your-reputation>

**Comment by sternschnaube** [comment]
Awesome 🥳
