### ISSUE TITLE
Hard Jade requirement.  I'm using WTHIT and it still crashes demanding Jade

### ISSUE THREAD

**Issue by tacogerbil** [Aton-Kish/your-reputation#24]
### Describe the bug

At startup it crashes stating there is a hard dependency on Jade.  I use WTHIT.

### To Reproduce

1.Install mod into 1.19.2 Fabric server using WTHIT
2. Start server

### Screenshots

For it to detect WTHIT and function as intended...

### Environment

- Minecraft: 1.19.2
- Fabric Loader: 0.14.21
- Fabric API: ?

### Logs

Pastebin the log [e.g. `logs/latest.log`] and link it below:

<!-- ```log
https://pastebin.com/0N2bnUwr
``` -->

### Additional context

Add any other context about the problem here.

**Comment by tacogerbil** [comment]
Hmmm swore I pasted the log and a pastebin url... Here again.. Just in case
https://pastebin.com/0N2bnUwr

**Comment by Aton-Kish** [comment]
Please check the mod file name. You are using the mod for Jade, aren't you? You need to install [WTHIT version](https://www.curseforge.com/minecraft/mc-mods/your-reputation/files/4447651).

**Comment by tacogerbil** [comment]
Ugh.. sorry.  I'll pay closer attention to the versions

**Comment by ColonelGerdauf** [comment]
Is it plausible to combine the two dependencies into a single mod, and have them set as an either-or mutex switch?
