### ISSUE TITLE
[Bug] Golems no longer attack Zombies

### ISSUE THREAD

**Issue by dandin87** [Aton-Kish/your-reputation#3]
### Describe the bug

Golems do not attack zombies. I assume your mixin is messing up the goal selection.

### To Reproduce

1. First step ... Spawn golem
2. Second step ... Spawn zombie

### Environment

- Minecraft: [1.18.1]
- Fabric Loader: [ 0.13.3]
- Fabric API: [e.g. 0.46.4+1.18]

### Additional context

All of Fabric 5 v1.0.0 modpack (I'm an AOF dev)
Removing Your Reputation returns functionality to the Golems.

**Comment by Aton-Kish** [comment]
Thanks for your report.
fixed in version 0.1.1+1.18
