### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by tacogerbil** [Aton-Kish/your-reputation#30]
### Describe the bug

Version 1.19.2 does NOT work with the required version of WTHIT.  Minecraft 1.19.2 demands I use Ver 5 of WTHIT.  Ver 7 is for 1.19.4.
![image](https://github.com/Aton-Kish/your-reputation/assets/12961907/cb63da57-761f-4a4f-8a48-40acfe4f7dea)
![image](https://github.com/Aton-Kish/your-reputation/assets/12961907/29183ba1-9bdd-4d94-9dd7-9d19d7280989)

### To Reproduce

1. Install described dependency on client.
2. Run the game.

### Expected behavior

Miinecraft to use both mods without any issue.  

### Environment

- Minecraft: 1.19.2
- Fabric Loader: 0.14.21
- Fabric API: 

### Logs

Pastebin the log [e.g. `logs/latest.log`] and link it below:

<!-- ```log
or paste the raw log here.
``` -->

### Additional context

Add any other context about the problem here.

**Comment by Aton-Kish** [comment]
v0.2.2+wthit.1.19 certainly doesn't work with Minecraft 1.19.2. corrected support versions metadata.
