### ISSUE TITLE
MC Mod Menu says to update to the Jade Version [Bug]

### ISSUE THREAD

**Issue by NolanHewitt** [Aton-Kish/your-reputation#33]
When using the WTHIT version of 1.19.2, the mod menu says there's a new update which links to the jade version. Not a big deal, but would be nice if this could be fixed.

**Comment by bons66** [comment]
Same bug with MC 1.20.1 + Jade Version.Links to the WTHIT version update.

**Comment by Aton-Kish** [comment]
From Minecraft 1.21+, I separated the mod project.

- WTHIT
  - curseforge: https://www.curseforge.com/minecraft/mc-mods/your-reputation-wthit
  - modrinth: https://modrinth.com/mod/your-reputation-wthit
- Jade
  - curseforge: https://www.curseforge.com/minecraft/mc-mods/your-reputation-jade
  - modrinth: https://modrinth.com/mod/your-reputation-jade
