### ISSUE TITLE
[Feature] Suggestion: Split into two separate Curseforge projects for the WTHIT/Jade versions

### ISSUE THREAD

**Issue by calloatti** [Aton-Kish/your-reputation#34]
### Describe the solution you'd like

Split into two separate Curseforge projects for the WTHIT/Jade versions

### Additional context

Having  WTHIT/Jade versions in the same Curseforge project breaks mod updaters that determine the latest available file based on loader/MC version using the Curseforge API

**Comment by calloatti** [comment]
See https://github.com/Aton-Kish/your-reputation/issues/33

**Comment by MrBiscuit921** [comment]
would be helpfull as when i try use it with jade minecraft crashes and says i need WTHIT

**Comment by Aton-Kish** [comment]
From Minecraft 1.21+, I separated the mod project.

- WTHIT
  - curseforge: https://www.curseforge.com/minecraft/mc-mods/your-reputation-wthit
  - modrinth: https://modrinth.com/mod/your-reputation-wthit
- Jade
  - curseforge: https://www.curseforge.com/minecraft/mc-mods/your-reputation-jade
  - modrinth: https://modrinth.com/mod/your-reputation-jade
